<Project>
    <PropertyGroup 
        Condition="'$(IsPackable)' == 'true' AND $([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)', 'net8.0'))"
    >
        <IsAotCompatible>true</IsAotCompatible>
    </PropertyGroup>
    <PropertyGroup
        Condition="'$(IsPackable)' == 'true' AND $([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)', 'net8.0')) AND '$(ProjectName)' != 'Juner.AspNetCore.Sequence'"
    >
        <VerifyReferenceAotCompatibility>true</VerifyReferenceAotCompatibility>
    </PropertyGroup>

    <PropertyGroup Condition="'$(IsPackable)' == 'true'">
        <Version>1.0.0-preview-2</Version>
        <FileVersion>1.0.0.2</FileVersion>
        <AssemblyVersion>1.0.0.2</AssemblyVersion>
        <Authors>juner</Authors>
        <Company>juner</Company>
        <RepositoryType>git</RepositoryType>
        <RepositoryUrl>https://github.com/juner/Sequence</RepositoryUrl>
        <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
    </PropertyGroup>

    <ItemGroup>    
        <PackageReference Update="coverlet.collector" Version="8.0.0" />
        <PackageReference Update="coverlet.msbuild" Version="8.0.0" />
        <PackageReference Update="MSTest" Version="4.1.0" />
        <PackageReference Update="Microsoft.AspNetCore.Mvc.Testing" Version="10.0.5" />
        <PackageReference Update="Microsoft.SourceLink.GitHub" Version="10.0.201" />
        <PackageReference Update="Microsoft.AspNetCore.OpenApi" Version="10.0.5" />
        <PackageReference Update="Microsoft.OpenApi" Version="3.4.0" />
        <PackageReference Update="System.IO.Pipelines" Version="8.0.0" />
        <PackageReference Update="BenchmarkDotNet" Version="0.15.8" />
    </ItemGroup>
    <ItemGroup Condition="'$(TargetFramework)' == 'net7.0' Or '$(TargetFramework)' == 'net6.0'">
        <PackageReference Update="MSTest" Version="3.10.1" />
        <PackageReference Update="System.IO.Pipelines" Version="[8.0.0,8.0.0]" />
    </ItemGroup>
    <ItemGroup Condition="'$(TargetFramework)' == 'net9.0'">
        <PackageReference Update="Microsoft.AspNetCore.Mvc.Testing" Version="9.0.14" />
    </ItemGroup>
    <ItemGroup Condition="'$(TargetFramework)' == 'net8.0'">
        <PackageReference Update="Microsoft.AspNetCore.Mvc.Testing" Version="8.0.25" />
    </ItemGroup>
    <ItemGroup Condition="'$(TargetFramework)' == 'net7.0'">
        <PackageReference Update="Microsoft.AspNetCore.Mvc.Testing" Version="7.0.0" />
    </ItemGroup>
</Project>