<Project>
    <ItemGroup>    
        <PackageReference Update="coverlet.collector" Version="8.0.0" />
        <PackageReference Update="coverlet.msbuild" Version="8.0.0" />
        <PackageReference Update="MSTest" Version="4.1.0" />
        <PackageReference Update="Microsoft.AspNetCore.Mvc.Testing" Version="10.0.5" />
        <PackageReference Update="Microsoft.SourceLink.GitHub" Version="10.0.201" />
        <PackageReference Update="Microsoft.AspNetCore.OpenApi" Version="10.0.5" />
        <PackageReference Update="Microsoft.OpenApi" Version="3.4.0" />
        <PackageReference Update="System.IO.Pipelines" Version="8.0.0" />
    </ItemGroup>
    <ItemGroup Condition="'$(TargetFramework)' == 'net7.0' Or '$(TargetFramework)' == 'net6.0'">
        <PackageReference Update="MSTest" Version="3.10.1" />
        <PackageReference Update="System.IO.Pipelines" Version="[8.0.0,8.0.0]" />
    </ItemGroup>
    <ItemGroup Condition="'$(TargetFramework)' == 'net9.0'">
        <PackageReference Update="Microsoft.AspNetCore.Mvc.Testing" Version="9.0.14" />
    </ItemGroup>
    <ItemGroup Condition="'$(TargetFramework)' == 'net8.0'">
        <PackageReference Update="Microsoft.AspNetCore.Mvc.Testing" Version="8.0.25" />
    </ItemGroup>
    <ItemGroup Condition="'$(TargetFramework)' == 'net7.0'">
        <PackageReference Update="Microsoft.AspNetCore.Mvc.Testing" Version="7.0.0" />
    </ItemGroup>
</Project>