<Project>

    <PropertyGroup>
        <TargetFrameworks>net7.0;net8.0;net9.0;net10.0</TargetFrameworks>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <Deterministic>true</Deterministic>
        <LangVersion>14</LangVersion>
        <CodeAnalysisTreatWarningsAsErrors>true</CodeAnalysisTreatWarningsAsErrors>
        <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
        <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
        <TrimmerSingleWarn>false</TrimmerSingleWarn>
    </PropertyGroup>

    <ItemGroup>
        <CompilerVisibleProperty Include="RootNamespace" />
        <CompilerVisibleProperty Include="ProjectDir" />
    </ItemGroup>
</Project>