<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsAotCompatible>true</IsAotCompatible>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Juner.Http.Sequence.Tests" />
  </ItemGroup>
  
  <ItemGroup>
    <ProjectReference Include="..\Sequence\Juner.Sequence.csproj" />
  </ItemGroup>

</Project>
