<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsAotCompatible>true</IsAotCompatible>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Juner.Sequence.Tests" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.IO.Pipelines" />
  </ItemGroup>

</Project>
